const pinyinMap: Record<string, string> = {
  '阿': 'a', '哎': 'ai', '安': 'an', '肮': 'ang', '凹': 'ao',
  '八': 'ba', '白': 'bai', '班': 'ban', '帮': 'bang', '包': 'bao',
  '杯': 'bei', '本': 'ben', '崩': 'beng', '逼': 'bi', '边': 'bian',
  '标': 'biao', '别': 'bie', '宾': 'bin', '兵': 'bing', '波': 'bo',
  '补': 'bu', '擦': 'ca', '猜': 'cai', '参': 'can', '仓': 'cang',
  '操': 'cao', '册': 'ce', '层': 'ceng', '查': 'cha', '拆': 'chai',
  '产': 'chan', '长': 'chang', '超': 'chao', '车': 'che', '沉': 'chen',
  '成': 'cheng', '吃': 'chi', '充': 'chong', '出': 'chu', '川': 'chuan',
  '创': 'chuang', '吹': 'chui', '春': 'chun', '词': 'ci', '从': 'cong',
  '凑': 'cou', '粗': 'cu', '催': 'cui', '存': 'cun', '错': 'cuo',
  '搭': 'da', '呆': 'dai', '单': 'dan', '当': 'dang', '刀': 'dao',
  '到': 'dao', '的': 'de', '灯': 'deng', '低': 'di', '地': 'di',
  '点': 'dian', '电': 'dian', '掉': 'diao', '爹': 'die', '丁': 'ding',
  '丢': 'diu', '东': 'dong', '都': 'dou', '读': 'du', '短': 'duan',
  '对': 'dui', '吨': 'dun', '多': 'duo', '额': 'e', '恩': 'en',
  '儿': 'er', '发': 'fa', '法': 'fa', '翻': 'fan', '方': 'fang',
  '飞': 'fei', '分': 'fen', '风': 'feng', '佛': 'fo', '否': 'fou',
  '夫': 'fu', '付': 'fu', '该': 'gai', '干': 'gan', '刚': 'gang',
  '高': 'gao', '告': 'gao', '哥': 'ge', '给': 'gei', '根': 'gen',
  '更': 'geng', '工': 'gong', '共': 'gong', '够': 'gou', '古': 'gu',
  '挂': 'gua', '怪': 'guai', '关': 'guan', '光': 'guang', '规': 'gui',
  '滚': 'gun', '国': 'guo', '哈': 'ha', '还': 'hai', '寒': 'han',
  '行': 'hang', '好': 'hao', '喝': 'he', '黑': 'hei', '很': 'hen',
  '红': 'hong', '后': 'hou', '乎': 'hu', '花': 'hua', '化': 'hua',
  '坏': 'huai', '欢': 'huan', '黄': 'huang', '回': 'hui', '会': 'hui',
  '混': 'hun', '活': 'huo', '火': 'huo', '鸡': 'ji', '几': 'ji',
  '己': 'ji', '加': 'jia', '间': 'jian', '见': 'jian', '将': 'jiang',
  '讲': 'jiang', '交': 'jiao', '叫': 'jiao', '接': 'jie', '节': 'jie',
  '界': 'jie', '金': 'jin', '仅': 'jin', '进': 'jin', '京': 'jing',
  '经': 'jing', '九': 'jiu', '酒': 'jiu', '就': 'jiu', '举': 'ju',
  '句': 'ju', '决': 'jue', '军': 'jun', '卡': 'ka', '开': 'kai',
  '看': 'kan', '康': 'kang', '考': 'kao', '科': 'ke', '可': 'ke',
  '客': 'ke', '肯': 'ken', '空': 'kong', '口': 'kou', '苦': 'ku',
  '快': 'kuai', '宽': 'kuan', '况': 'kuang', '亏': 'kui', '困': 'kun',
  '扩': 'kuo', '拉': 'la', '来': 'lai', '兰': 'lan', '浪': 'lang',
  '老': 'lao', '乐': 'le', '了': 'le', '累': 'lei', '冷': 'leng',
  '里': 'li', '力': 'li', '利': 'li', '连': 'lian', '脸': 'lian',
  '练': 'lian', '良': 'liang', '两': 'liang', '亮': 'liang', '列': 'lie',
  '林': 'lin', '灵': 'ling', '另': 'ling', '流': 'liu', '六': 'liu',
  '龙': 'long', '楼': 'lou', '路': 'lu', '旅': 'lv', '绿': 'lv',
  '乱': 'luan', '论': 'lun', '落': 'luo', '妈': 'ma', '马': 'ma',
  '吗': 'ma', '买': 'mai', '满': 'man', '忙': 'mang', '毛': 'mao',
  '冒': 'mao', '没': 'mei', '美': 'mei', '门': 'men', '梦': 'meng',
  '米': 'mi', '面': 'mian', '苗': 'miao', '秒': 'miao', '民': 'min',
  '明': 'ming', '名': 'ming', '命': 'ming', '母': 'mu', '木': 'mu',
  '目': 'mu', '那': 'na', '男': 'nan', '南': 'nan', '难': 'nan',
  '脑': 'nao', '内': 'nei', '能': 'neng', '你': 'ni', '年': 'nian',
  '鸟': 'niao', '牛': 'niu', '农': 'nong', '女': 'nv', '暖': 'nuan',
  '欧': 'ou', '怕': 'pa', '拍': 'pai', '排': 'pai', '盘': 'pan',
  '跑': 'pao', '配': 'pei', '朋': 'peng', '碰': 'peng', '皮': 'pi',
  '片': 'pian', '票': 'piao', '拼': 'pin', '品': 'pin', '平': 'ping',
  '瓶': 'ping', '破': 'po', '七': 'qi', '期': 'qi', '齐': 'qi',
  '其': 'qi', '起': 'qi', '气': 'qi', '前': 'qian', '钱': 'qian',
  '强': 'qiang', '桥': 'qiao', '切': 'qie', '亲': 'qin', '青': 'qing',
  '清': 'qing', '情': 'qing', '请': 'qing', '穷': 'qiong', '秋': 'qiu',
  '求': 'qiu', '球': 'qiu', '区': 'qu', '去': 'qu', '全': 'quan',
  '权': 'quan', '缺': 'que', '确': 'que', '群': 'qun', '然': 'ran',
  '让': 'rang', '热': 're', '人': 'ren', '日': 'ri', '容': 'rong',
  '如': 'ru', '入': 'ru', '软': 'ruan', '瑞': 'rui', '润': 'run',
  '若': 'ruo', '三': 'san', '散': 'san', '色': 'se', '森': 'sen',
  '杀': 'sha', '山': 'shan', '伤': 'shang', '上': 'shang', '少': 'shao',
  '设': 'she', '社': 'she', '身': 'shen', '深': 'shen', '什': 'shen',
  '生': 'sheng', '声': 'sheng', '师': 'shi', '十': 'shi', '石': 'shi',
  '时': 'shi', '实': 'shi', '食': 'shi', '史': 'shi', '始': 'shi',
  '世': 'shi', '市': 'shi', '事': 'shi', '是': 'shi', '室': 'shi',
  '收': 'shou', '手': 'shou', '首': 'shou', '受': 'shou', '书': 'shu',
  '数': 'shu', '双': 'shuang', '谁': 'shui', '水': 'shui', '顺': 'shun',
  '说': 'shuo', '思': 'si', '死': 'si', '四': 'si', '松': 'song',
  '送': 'song', '搜': 'sou', '速': 'su', '算': 'suan', '虽': 'sui',
  '岁': 'sui', '孙': 'sun', '所': 'suo', '他': 'ta', '她': 'ta',
  '它': 'ta', '台': 'tai', '太': 'tai', '谈': 'tan', '汤': 'tang',
  '堂': 'tang', '糖': 'tang', '逃': 'tao', '特': 'te', '疼': 'teng',
  '提': 'ti', '题': 'ti', '体': 'ti', '天': 'tian', '田': 'tian',
  '条': 'tiao', '跳': 'tiao', '铁': 'tie', '听': 'ting', '停': 'ting',
  '通': 'tong', '同': 'tong', '头': 'tou', '图': 'tu', '土': 'tu',
  '团': 'tuan', '推': 'tui', '退': 'tui', '拖': 'tuo', '外': 'wai',
  '完': 'wan', '万': 'wan', '王': 'wang', '网': 'wang', '忘': 'wang',
  '往': 'wang', '望': 'wang', '危': 'wei', '微': 'wei', '为': 'wei',
  '围': 'wei', '伟': 'wei', '未': 'wei', '位': 'wei', '味': 'wei',
  '文': 'wen', '问': 'wen', '我': 'wo', '五': 'wu', '午': 'wu',
  '物': 'wu', '务': 'wu', '西': 'xi', '希': 'xi', '息': 'xi',
  '习': 'xi', '喜': 'xi', '系': 'xi', '细': 'xi', '下': 'xia',
  '夏': 'xia', '先': 'xian', '鲜': 'xian', '现': 'xian', '线': 'xian',
  '相': 'xiang', '香': 'xiang', '想': 'xiang', '向': 'xiang', '象': 'xiang',
  '像': 'xiang', '小': 'xiao', '校': 'xiao', '笑': 'xiao', '些': 'xie',
  '写': 'xie', '谢': 'xie', '心': 'xin', '新': 'xin', '信': 'xin',
  '星': 'xing', '形': 'xing', '性': 'xing', '兄': 'xiong', '休': 'xiu',
  '修': 'xiu', '秀': 'xiu', '需': 'xu', '许': 'xu', '续': 'xu',
  '选': 'xuan', '学': 'xue', '雪': 'xue', '血': 'xue', '寻': 'xun',
  '训': 'xun', '呀': 'ya', '牙': 'ya', '亚': 'ya', '言': 'yan',
  '严': 'yan', '研': 'yan', '眼': 'yan', '演': 'yan', '央': 'yang',
  '羊': 'yang', '阳': 'yang', '样': 'yang', '要': 'yao', '药': 'yao',
  '也': 'ye', '业': 'ye', '夜': 'ye', '一': 'yi', '衣': 'yi',
  '医': 'yi', '已': 'yi', '以': 'yi', '亿': 'yi', '义': 'yi',
  '艺': 'yi', '易': 'yi', '意': 'yi', '因': 'yin', '音': 'yin',
  '银': 'yin', '应': 'ying', '英': 'ying', '影': 'ying', '硬': 'ying',
  '哟': 'yo', '用': 'yong', '有': 'you', '友': 'you', '又': 'you',
  '右': 'you', '鱼': 'yu', '于': 'yu', '雨': 'yu', '语': 'yu',
  '玉': 'yu', '育': 'yu', '元': 'yuan', '园': 'yuan', '员': 'yuan',
  '原': 'yuan', '远': 'yuan', '院': 'yuan', '愿': 'yuan', '月': 'yue',
  '越': 'yue', '云': 'yun', '运': 'yun', '在': 'zai', '早': 'zao',
  '怎': 'zen', '增': 'zeng', '站': 'zhan', '张': 'zhang', '找': 'zhao',
  '照': 'zhao', '这': 'zhe', '真': 'zhen', '整': 'zheng', '正': 'zheng',
  '知': 'zhi', '之': 'zhi', '直': 'zhi', '只': 'zhi', '纸': 'zhi',
  '指': 'zhi', '至': 'zhi', '中': 'zhong', '种': 'zhong', '重': 'zhong',
  '州': 'zhou', '周': 'zhou', '主': 'zhu', '住': 'zhu', '注': 'zhu',
  '祝': 'zhu', '专': 'zhuan', '转': 'zhuan', '装': 'zhuang', '准': 'zhun',
  '桌': 'zhuo', '自': 'zi', '字': 'zi', '走': 'zou', '最': 'zui',
  '昨': 'zuo', '作': 'zuo', '做': 'zuo', '坐': 'zuo', '座': 'zuo',
  '草': 'cao', '树': 'shu', '叶': 'ye', '果': 'guo', '竹': 'zhu',
  '柏': 'bai', '柳': 'liu', '桃': 'tao', '梅': 'mei', '菊': 'ju',
  '荷': 'he', '莲': 'lian', '桂': 'gui', '樱': 'ying', '梨': 'li',
  '杏': 'xing', '枣': 'zao', '柿': 'shi', '橘': 'ju', '柚': 'you',
  '柠': 'ning', '檬': 'meng', '葡': 'pu', '萄': 'tao', '蕉': 'jiao',
  '菠': 'bo', '萝': 'luo', '芒': 'mang', '荔': 'li', '枝': 'zhi',
  '瓜': 'gua', '藤': 'teng', '蔓': 'man', '苔': 'tai',
  '藓': 'xian', '蕨': 'jue', '萍': 'ping', '藻': 'zao', '菇': 'gu',
  '菌': 'jun', '蘑': 'mo', '葱': 'cong', '蒜': 'suan', '姜': 'jiang',
  '椒': 'jiao', '芹': 'qin', '菜': 'cai', '卜': 'bo', '茄': 'qie',
  '薯': 'shu', '芋': 'yu', '笋': 'sun', '豆': 'dou', '豌': 'wan',
  '蚕': 'can', '麻': 'ma', '棉': 'mian', '稻': 'dao', '麦': 'mai',
  '粟': 'su', '黍': 'shu', '粱': 'liang', '谷': 'gu', '茶': 'cha',
  '烟': 'yan', '芝': 'zhi', '芦': 'lu', '苇': 'wei', '蒲': 'pu',
  '艾': 'ai', '蒿': 'hao', '藜': 'li', '苋': 'xian', '荠': 'ji',
  '蔷': 'qiang', '薇': 'wei', '茉': 'mo', '莉': 'li', '牡': 'mu',
  '丹': 'dan', '芍': 'shao', '玫': 'mei', '瑰': 'gui', '芙': 'fu',
  '蓉': 'rong', '葵': 'kui', '萱': 'xuan', '蕙': 'hui', '芷': 'zhi',
  '藦': 'mo', '蘅': 'heng', '蘼': 'mi', '芭': 'ba', '梧': 'wu',
  '桐': 'tong', '榆': 'yu', '槐': 'huai', '樟': 'zhang', '杉': 'shan',
  '枫': 'feng', '桦': 'hua', '栎': 'li', '檀': 'tan', '楠': 'nan',
  '梓': 'zi', '楸': 'qiu', '椴': 'duan', '槭': 'qi', '枥': 'li',
  '枸': 'gou', '杞': 'qi', '栾': 'luan', '榕': 'rong', '橡': 'xiang',
  '椿': 'chun', '樗': 'chu', '楝': 'lian', '榉': 'ju', '朴': 'po',
  '桤': 'qi',
}

export function getChinesePinyin(char: string): string {
  return pinyinMap[char] || char.toLowerCase()
}

export function getPinyinInitial(char: string): string {
  const pinyin = getChinesePinyin(char)
  return pinyin.charAt(0)
}

export function toPinyin(text: string): string {
  let result = ''
  for (const char of text) {
    result += getChinesePinyin(char)
  }
  return result
}

export function toPinyinInitials(text: string): string {
  let result = ''
  for (const char of text) {
    if (/[\u4e00-\u9fa5]/.test(char)) {
      result += getPinyinInitial(char)
    } else {
      result += char.toLowerCase()
    }
  }
  return result
}
